"use client";

import { useCallback, useRef } from "react";
import { useCortexStore } from "@/store/useCortexStore";
import type { DebateMessage, WSEvent } from "@/types/types";

const API_BASE = "http://localhost:8000";

// ─── REST: Upload Files + Run Diagnosis ─────────────────────────────

export function useUploadAndStream() {
  const {
    setPhase,
    setSessionId,
    setError,
    setIsLoading,
  } = useCortexStore();

  const { connect } = useDebateSocket();
  const addMessage = useCortexStore((s) => s.addMessage);

  const uploadAndStream = useCallback(
    async (
      files: File[],
      patientText: string,
      fileLabels: string,
      maxRounds: number = 3
    ) => {
      setIsLoading(true);
      setError(null);

      // Switch purely to real-time WebSockets instantly so the user sees "something is going on"
      setPhase("COURTROOM");
      addMessage({
        agent_id: "system",
        content: "Initiating OCR document extraction...",
        timestamp: new Date().toISOString()
      } as DebateMessage);

      try {
        const formData = new FormData();
        files.forEach((f) => formData.append("files", f));
        formData.append("patient_text", patientText);
        formData.append("file_labels", fileLabels);

        const res = await fetch(`${API_BASE}/api/v1/extract-files`, {
          method: "POST",
          body: formData,
        });

        if (!res.ok) {
          const errBody = await res.json().catch(() => ({}));
          throw new Error(errBody.detail || `Server error ${res.status}`);
        }

        const data = await res.json();
        setSessionId(data.session_id);

        addMessage({
           agent_id: "system",
           content: "OCR complete. Initiating Omni Cortex-X diagnostic protocol...",
           timestamp: new Date().toISOString()
        } as DebateMessage);

        connect(data.patient_data, maxRounds, data.ocr_extractions);

      } catch (err) {
        setError(err instanceof Error ? err.message : "Upload failed");
      } finally {
        setIsLoading(false);
      }
    },
    [setPhase, setSessionId, setError, setIsLoading, connect, addMessage]
  );

  return { uploadAndStream };
}

// ─── WebSocket: Live Debate Streaming ───────────────────────────────

export function useDebateSocket() {
  const wsRef = useRef<WebSocket | null>(null);

  const {
    setPhase,
    setSessionId,
    addMessage,
    updateScores,
    setActiveAgent,
    setCurrentRound,
    setHypotheses,
    setVerdict,
    setMissingData,
    setError,
  } = useCortexStore();

  const connect = useCallback(
    (patientData: Record<string, unknown>, maxRounds: number = 5, ocrExtractions: any = null) => {
      // Close any existing connection
      if (wsRef.current) {
        wsRef.current.close();
      }

      const ws = new WebSocket(`${API_BASE.replace("http", "ws")}/ws/diagnose`);
      wsRef.current = ws;

      ws.onopen = () => {
        ws.send(
          JSON.stringify({
            patient_data: patientData,
            ocr_extractions: ocrExtractions,
            max_rounds: maxRounds,
          })
        );
      };

      ws.onmessage = (event) => {
        let raw: WSEvent | null = null;
        try {
           raw = JSON.parse(event.data);
        } catch (e) {
           return;
        }

        if (!raw) return;

        switch (raw.type) {
          case "session_start":
            setSessionId(raw.session_id || "");
            break;

          case "phase_update":
            if (raw.round) setCurrentRound(raw.round);
            break;

          case "triage_complete": {
            const hypotheses = (raw.data?.hypotheses as typeof useCortexStore.getState extends () => infer S ? S extends { hypotheses: infer H } ? H : never : never) || [];
            setHypotheses(hypotheses);
            // Pre-seed scores from triage
            const initialScores: Record<string, number> = {};
            hypotheses.forEach((h: any) => {
              if (h.diagnosis && h.confidence !== undefined) {
                initialScores[h.diagnosis] = Math.round(h.confidence * 100);
              }
            });
            updateScores(initialScores);
            break;
          }

          case "peer_rating_complete": {
            const rawScores = raw.advocate_scores as Record<string, number> | undefined;
            if (rawScores) {
              const mappedScores: Record<string, number> = {};
              for (const [id, score] of Object.entries(rawScores)) {
                // Extract diagnosis from advocate_0_DiagnosisName
                const parts = id.split("_", 3);
                const diag = parts.length > 2 ? parts.slice(2).join("_") : id;
                mappedScores[diag] = Math.round((Math.max(0, Math.min(10, score))) * 10);
              }
              useCortexStore.getState().updateScores(mappedScores);
            }
            break;
          }

          // Use the nicely formatted chat_messages generated by the backend
          case "chat_message": {
            const msg = Object.assign({}, raw, {
               agent_id: raw.agent_id || "system",
            }) as unknown as DebateMessage & { agent_name: string; agent_role: string; agent_emoji?: string };
            
            if (msg) {
              setActiveAgent(msg.agent_id);
              addMessage(msg);
            }
            break;
          }

          case "consensus_event": {
            const scores = raw.data?.confidence_scores as Record<string, number>;
            if (scores) updateScores(scores);
            break;
          }

          case "final_report": {
            const diagnosis = raw.data?.diagnosis as typeof useCortexStore.getState extends () => infer S ? S extends { verdict: infer V } ? V : never : never;
            if (diagnosis) {
              setVerdict(diagnosis);
              setPhase("VERDICT");
            }
            break;
          }

          case "error":
            setError(raw.error || "Unknown WebSocket error");
            break;

          case "complete":
            setActiveAgent(null);
            // Don't auto-set phase to verdict here, wait for final_report event
            break;
        }
      };

      ws.onerror = () => {
        setError("WebSocket connection failed. Is the backend running?");
      };

      ws.onclose = () => {
        wsRef.current = null;
      };
    },
    [
      setPhase,
      setSessionId,
      addMessage,
      updateScores,
      setActiveAgent,
      setCurrentRound,
      setHypotheses,
      setVerdict,
      setMissingData,
      setError,
    ]
  );

  const disconnect = useCallback(() => {
    if (wsRef.current) {
      wsRef.current.close();
      wsRef.current = null;
    }
  }, []);

  return { connect, disconnect };
}
